export type BackendContractStatus = "current" | "process-memory" | "prompt-preview" | "chunked-buffer" | "unsupported" | "planned" | "deprecated";

export type BackendContractSourceKind = "route" | "websocket" | "session-tool" | "shared-type";

export interface BackendContractCapability {
  readonly id: string;
  readonly userCapability: string;
  readonly entry: string;
  readonly status: BackendContractStatus;
  readonly dataSource: string;
  readonly failureBoundary: string;
  readonly frontendRule: string;
  readonly source: {
    readonly kind: BackendContractSourceKind;
    readonly file: string;
    readonly exportName?: string;
  };
}

export const BACKEND_CONTRACT_CAPABILITIES: readonly BackendContractCapability[] = [
  {
    id: "books.list",
    userCapability: "书籍列表",
    entry: "GET /api/books",
    status: "current",
    dataSource: "book.json + chapters index",
    failureBoundary: "route 失败时返回真实错误，前端显示空状态/错误。",
    frontendRule: "Sidebar 叙事线唯一来源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/storage.ts", exportName: "createStorageRouter" },
  },
  {
    id: "books.detail",
    userCapability: "书籍详情",
    entry: "GET /api/books/:id",
    status: "current",
    dataSource: "书籍配置 + 章节索引",
    failureBoundary: "不存在或非法 bookId 返回真实 4xx。",
    frontendRule: "Workbench 主数据来源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/storage.ts", exportName: "createStorageRouter" },
  },
  {
    id: "books.create-status",
    userCapability: "建书状态",
    entry: "GET /api/books/:id/create-status",
    status: "process-memory",
    dataSource: "当前进程 create state + 文件产物",
    failureBoundary: "进程重启后只以书籍文件是否存在为准。",
    frontendRule: "显示临时/可恢复边界，不当作长期状态。",
    source: { kind: "route", file: "packages/studio/src/api/routes/storage.ts", exportName: "createStorageRouter" },
  },
  {
    id: "sessions.active",
    userCapability: "活跃会话列表",
    entry: "GET /api/sessions?sort=recent&status=active",
    status: "current",
    dataSource: "session store",
    failureBoundary: "失败返回真实错误或空列表，不填充 demo 会话。",
    frontendRule: "Sidebar 叙述者唯一来源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.lifecycle.continue",
    userCapability: "继续最近会话",
    entry: "GET /api/sessions/lifecycle/latest?projectId=&chapterId=",
    status: "current",
    dataSource: "session lifecycle service + session store",
    failureBoundary: "找不到 scoped active session 返回真实 404，不创建空会话。",
    frontendRule: "ResumePicker/SessionCenter 继续最近会话入口唯一来源；必须按 Backend Contract client 打开返回 session。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.lifecycle.fork",
    userCapability: "Fork 历史会话",
    entry: "POST /api/sessions/:id/fork",
    status: "current",
    dataSource: "session lifecycle service + session chat snapshot",
    failureBoundary: "源 session 不存在返回真实 404；成功只写入 system summary，不复制完整历史。",
    frontendRule: "ForkDialog 只能打开后端返回的新 sessionId，不得本地伪造。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.lifecycle.restore",
    userCapability: "归档会话恢复继续",
    entry: "POST /api/sessions/:id/restore",
    status: "current",
    dataSource: "session lifecycle service + session store",
    failureBoundary: "找不到会话返回真实 404；归档会话显式恢复为 active 后继续。",
    frontendRule: "归档 session 默认只读，只有显式恢复后才允许继续写入。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.compact",
    userCapability: "会话上下文压缩",
    entry: "POST /api/sessions/:id/compact",
    status: "current",
    dataSource: "session compact service + session chat snapshot",
    failureBoundary: "会话不存在返回真实 404；历史不足返回 400 且保留原历史。",
    frontendRule: "`/compact` 必须走 Backend Contract client 和 session compact service，成功后刷新 snapshot 并展示 summary/budget。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.headless-chat",
    userCapability: "Headless stream-json 会话 API",
    entry: "POST /api/sessions/headless-chat",
    status: "current",
    dataSource: "session headless chat service + AgentTurnRuntime + session history store",
    failureBoundary: "支持 text / stream-json input；outputFormat=stream-json 返回 NDJSON；noSessionPersistence 使用 ephemeral sessionId 且不写 history；pending confirmation 返回 202 与 permission_request/result envelope；maxTurns=0 返回 max_turns。",
    frontendRule: "CLI/headless consumer 必须使用 Backend Contract client 或该登记 API；不得另起 direct agent loop。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.memory.status",
    userCapability: "会话 Memory 写入边界状态",
    entry: "GET /api/sessions/:id/memory/status",
    status: "current",
    dataSource: "session memory boundary service + readonly fallback when writer is not configured",
    failureBoundary: "会话不存在返回真实 404；memory writer 未接入时返回 readonly，不写假成功。",
    frontendRule: "UI 必须展示只读/未接入状态；不得把临时剧情草稿自动写入长期 memory。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.memory.write",
    userCapability: "会话 Memory 审计写入",
    entry: "POST /api/sessions/:id/memory",
    status: "current",
    dataSource: "session memory boundary service + injectable memory writer",
    failureBoundary: "writer 缺失或失败返回可恢复错误；偏好/项目事实必须带确认和审计来源，临时剧情返回 skipped。",
    frontendRule: "只允许通过 Backend Contract client 提交分类后的 memory candidate，并显示审计/失败结果。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.crud",
    userCapability: "会话 CRUD",
    entry: "POST/PUT/DELETE /api/sessions/:id?",
    status: "current",
    dataSource: "session service",
    failureBoundary: "找不到会话返回 404，创建返回真实 session。",
    frontendRule: "创建、更新、归档、恢复、新建绑定会话。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.chat.state",
    userCapability: "会话初始快照",
    entry: "GET /api/sessions/:id/chat/state",
    status: "current",
    dataSource: "session history + runtime state",
    failureBoundary: "会话不存在返回 404。",
    frontendRule: "打开会话先 hydrate，不能构造假消息。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.chat.history",
    userCapability: "增量历史",
    entry: "GET /api/sessions/:id/chat/history?sinceSeq=",
    status: "current",
    dataSource: "持久化 chat history",
    failureBoundary: "history gap 使用 resetRequired，不拼接错乱消息。",
    frontendRule: "WebSocket 断线 replay 来源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.chat.websocket",
    userCapability: "实时会话 WebSocket",
    entry: "WS /api/sessions/:id/chat",
    status: "current",
    dataSource: "session chat runtime",
    failureBoundary: "保留 session:error / recovery envelope。",
    frontendRule: "处理 snapshot/state/message/stream/error，不伪造运行状态。",
    source: { kind: "websocket", file: "packages/studio/src/api/server.ts", exportName: "setupSessionWebSocket" },
  },
  {
    id: "sessions.tools.confirm",
    userCapability: "工具确认门",
    entry: "GET /api/sessions/:id/tools + POST /api/sessions/:id/tools/:toolName/confirm",
    status: "current",
    dataSource: "session tool state + sessionConfig.toolPolicy",
    failureBoundary: "确认失败返回真实错误，批准/拒绝后刷新 snapshot。",
    frontendRule: "内联确认门，不用假成功按钮；ask 工具策略必须显示 permission-required 确认门。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "sessions.tools.policy",
    userCapability: "细粒度工具权限策略",
    entry: "GET /api/sessions/:id/tools + PUT /api/sessions/:id sessionConfig.toolPolicy",
    status: "current",
    dataSource: "sessionConfig.toolPolicy + session tool policy matcher",
    failureBoundary: "deny 返回 policy-denied；ask 返回 permission-required 确认门；全部工具被禁用返回 policy-disabled，不发送不可执行工具 schema。",
    frontendRule: "状态栏展示 allow/deny/ask 概览；前端只能通过 session domain client 持久化 toolPolicy。",
    source: { kind: "route", file: "packages/studio/src/api/routes/session.ts", exportName: "sessionRouter" },
  },
  {
    id: "chapters.detail",
    userCapability: "章节读取/保存",
    entry: "GET/PUT /api/books/:id/chapters/:num",
    status: "current",
    dataSource: "chapters/*.md + index",
    failureBoundary: "章节不存在、非法 bookId 或保存失败返回真实错误。",
    frontendRule: "可编辑章节 viewer/editor 的唯一保存入口。",
    source: { kind: "route", file: "packages/studio/src/api/routes/storage.ts", exportName: "createStorageRouter" },
  },
  {
    id: "resources.rewind.preview",
    userCapability: "资源 Rewind 预览",
    entry: "GET /api/books/:id/checkpoints/:checkpointId/rewind/preview",
    status: "current",
    dataSource: ".novelfork/checkpoints checkpoint manifest + resource snapshots + current files",
    failureBoundary: "checkpoint 不存在返回 404；预览返回当前 hash、snapshot hash、diff 与 risk，不写文件。",
    frontendRule: "恢复前必须显示受影响资源和风险；不得本地拼接 checkpoint 路径。",
    source: { kind: "route", file: "packages/studio/src/api/routes/storage.ts", exportName: "createStorageRouter" },
  },
  {
    id: "resources.rewind.apply",
    userCapability: "资源 Rewind 应用",
    entry: "POST /api/books/:id/checkpoints/:checkpointId/rewind/apply",
    status: "current",
    dataSource: ".novelfork/checkpoints checkpoint manifest + safety checkpoint + rewind audit",
    failureBoundary: "无确认返回 pending-confirmation；拒绝不写文件；批准时检查 expectedCurrentHashes，冲突或资源移动返回真实错误。",
    frontendRule: "必须走确认门；apply 后刷新资源树/会话工具结果，不伪造恢复成功。",
    source: { kind: "route", file: "packages/studio/src/api/routes/storage.ts", exportName: "createStorageRouter" },
  },
  {
    id: "candidates.accept",
    userCapability: "候选稿接受",
    entry: "POST /api/books/:id/candidates/:candidateId/accept",
    status: "current",
    dataSource: "generated-candidates + chapters/drafts",
    failureBoundary: "action 必须是 merge/replace/draft；候选不存在返回 404。",
    frontendRule: "候选稿只能通过显式 merge/replace/draft 应用。",
    source: { kind: "route", file: "packages/studio/src/api/routes/chapter-candidates.ts", exportName: "createChapterCandidatesRouter" },
  },
  {
    id: "drafts.crud",
    userCapability: "草稿 CRUD",
    entry: "GET/POST/PUT/DELETE /api/books/:id/drafts*",
    status: "current",
    dataSource: "drafts/ files + index",
    failureBoundary: "草稿不存在返回 404，创建缺 title/content 返回 400。",
    frontendRule: "草稿资源 CRUD；不得等同 AI draft 异步动作。",
    source: { kind: "route", file: "packages/studio/src/api/routes/chapter-candidates.ts", exportName: "createChapterCandidatesRouter" },
  },
  {
    id: "narrative.line.snapshot",
    userCapability: "叙事线只读快照",
    entry: "GET /api/books/:bookId/narrative-line 或 narrative.read_line",
    status: "current",
    dataSource: "章节/经纬/冲突/伏笔聚合",
    failureBoundary: "聚合失败显示真实错误；变更写入需走 propose/apply。",
    frontendRule: "只读图谱/画布 artifact。",
    source: { kind: "route", file: "packages/studio/src/api/routes/narrative-line.ts", exportName: "createNarrativeLineRouter" },
  },
  {
    id: "session-native.write-next",
    userCapability: "Session-native 写下一章",
    entry: "cockpit.get_snapshot → pgi.generate_questions → guided.enter/guided.exit → candidate.create_chapter",
    status: "current",
    dataSource: "session tools + candidate service",
    failureBoundary: "模型不可用或工具失败时返回 tool_result 失败，不写正式章节。",
    frontendRule: "首选链路；成功只进入候选区。",
    source: { kind: "session-tool", file: "packages/studio/src/api/lib/session-tool-registry.ts", exportName: "getAllSessionToolDefinitions" },
  },
  {
    id: "writing-modes.preview",
    userCapability: "Writing modes 预览",
    entry: "POST /api/books/:bookId/inline-write",
    status: "prompt-preview",
    dataSource: "LLM 或 prompt preview fallback",
    failureBoundary: "无 session LLM 返回 prompt-preview，不代表生成正文。",
    frontendRule: "只允许预览、复制或显式 apply。",
    source: { kind: "route", file: "packages/studio/src/api/routes/writing-modes.ts", exportName: "createWritingModesRouter" },
  },
  {
    id: "writing-modes.apply",
    userCapability: "Writing modes 安全应用",
    entry: "POST /api/books/:bookId/writing-modes/apply",
    status: "current",
    dataSource: "candidate/draft 写入",
    failureBoundary: "正式章节 insert/replace 首版转候选，避免无确认覆盖。",
    frontendRule: "AI 输出默认 candidate/draft/preview，正式正文写入需显式动作。",
    source: { kind: "route", file: "packages/studio/src/api/routes/writing-modes.ts", exportName: "createWritingModesRouter" },
  },
  {
    id: "ai.complete.chunked-buffer",
    userCapability: "行内补全 SSE",
    entry: "POST /api/ai/complete",
    status: "chunked-buffer",
    dataSource: "完整 AI 结果后分块发送",
    failureBoundary: "不是上游原生流式；失败保留错误 envelope。",
    frontendRule: "可流式显示但标注 chunked-buffer 边界。",
    source: { kind: "route", file: "packages/studio/src/api/routes/ai.ts", exportName: "createAIRouter" },
  },
  {
    id: "legacy.pipeline-runs.process-memory",
    userCapability: "Pipeline 可视化运行态",
    entry: "GET /api/pipeline*",
    status: "process-memory",
    dataSource: "routes/pipeline.ts 当前进程 pipelineRuns Map",
    failureBoundary: "run/stage/list/SSE 均只代表当前进程临时状态，重启后不能恢复。",
    frontendRule: "可作为调试透明面板读取；不得把 run history 描述为持久化事实源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/pipeline.ts", exportName: "createPipelineRouter" },
  },
  {
    id: "legacy.monitor.unsupported",
    userCapability: "Monitor 状态与日志",
    entry: "GET /api/monitor/status + WS /api/monitor/logs",
    status: "unsupported",
    dataSource: "daemon/runtime 事件事实源尚未接入",
    failureBoundary: "HTTP 返回 501 unsupported；WebSocket 发送 unsupported 事件后关闭，不伪造 stopped 或实时日志。",
    frontendRule: "UI 必须显示未接入说明或禁用入口；接入真实事实源前不得恢复绿色状态。",
    source: { kind: "route", file: "packages/studio/src/api/routes/monitor.ts", exportName: "createMonitorRouter" },
  },
  {
    id: "legacy.ai-agent.unsupported",
    userCapability: "已退役 direct agent loop",
    entry: "retired POST /api/agent",
    status: "unsupported",
    dataSource: "legacy-source-retirement-v1 Task 9 已从 createAIRouter 移除 exact POST /api/agent handler；/api/agent/config 是独立 current route。",
    failureBoundary: "旧响应 envelope 与 session-native /api/sessions 工具链不一致；恢复前必须重新创建 current contract、route tests 与前端 client。",
    frontendRule: "新前端必须使用 /api/sessions、/api/exec 或 session tools；不得重新调用 retired /api/agent。",
    source: { kind: "route", file: "packages/studio/src/api/backend-contract-matrix.ts" },
  },
  {
    id: "legacy.export.deprecated",
    userCapability: "旧导出读取/保存入口",
    entry: "GET/POST /api/books/:id/export + POST /api/books/:id/export-save",
    status: "deprecated",
    dataSource: "storage export service；README/docs 与 server integration tests 仍引用",
    failureBoundary: "当前仍是真实导出内容，但统一导出范围选择与新前端合同尚未收敛。",
    frontendRule: "保留到统一导出 contract 落地；新 UI 接入前需补 matrix/client/adapter 与 route tests。",
    source: { kind: "route", file: "packages/studio/src/api/routes/storage.ts", exportName: "createStorageRouter" },
  },
  {
    id: "legacy.ai-panels.deprecated",
    userCapability: "旧 AI 辅助面板接口",
    entry: "POST /api/ai/transform|context-assembly|outline",
    status: "deprecated",
    dataSource: "legacy ContextPanel/OutlinePanel/InkEditor 相关路径；app-next 当前合同主线不依赖这些直连接口",
    failureBoundary: "调用直接走 LLM/文件上下文，未纳入 session tool 确认门或 resource adapter。",
    frontendRule: "新前端应优先通过 session tools、writing action adapter 或 resource contract 接入，不新增直连组件依赖。",
    source: { kind: "route", file: "packages/studio/src/api/routes/ai.ts", exportName: "createAIRouter" },
  },
  {
    id: "legacy.disabled-routers.unsupported",
    userCapability: "禁用旧 Router",
    entry: "unmounted /api/poison-detector* 和 /api/hooks*",
    status: "unsupported",
    dataSource: "legacy-source-retirement-v1 Task 8 已删除未挂载 route 文件，并从 routes/index.ts、server.ts 与 tsconfig exclude 中移除残留。",
    failureBoundary: "未挂载即不可调用；后续恢复必须重新创建 current route 并补 contract。",
    frontendRule: "前端不得显示可用入口；已删除源码只能通过 Git 历史追溯。",
    source: { kind: "route", file: "packages/studio/src/api/backend-contract-matrix.ts" },
  },
  {
    id: "providers.status",
    userCapability: "Provider 状态",
    entry: "GET /api/providers/status",
    status: "current",
    dataSource: "runtime provider store",
    failureBoundary: "失败显示真实错误，不展示虚拟模型 fallback。",
    frontendRule: "模型状态栏来源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/providers.ts", exportName: "createProvidersRouter" },
  },
  {
    id: "providers.models",
    userCapability: "模型池",
    entry: "GET /api/providers/models",
    status: "current",
    dataSource: "enabled provider/model/account",
    failureBoundary: "adapter failure code 原样展示。",
    frontendRule: "模型选择器唯一来源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/providers.ts", exportName: "createProvidersRouter" },
  },
  {
    id: "providers.summary",
    userCapability: "Provider 概览",
    entry: "GET /api/providers/summary",
    status: "current",
    dataSource: "provider runtime store",
    failureBoundary: "不回传明文 apiKey。",
    frontendRule: "设置页统计来源。",
    source: { kind: "route", file: "packages/studio/src/api/routes/providers.ts", exportName: "createProvidersRouter" },
  },
  {
    id: "providers.model.test",
    userCapability: "模型测试",
    entry: "POST /api/providers/:id/models/:modelId/test",
    status: "current",
    dataSource: "provider adapter + runtime store",
    failureBoundary: "保留 unsupported/auth-missing/config-missing/upstream-error/network-error。",
    frontendRule: "显示真实失败 envelope，不吞 code。",
    source: { kind: "route", file: "packages/studio/src/api/routes/providers.ts", exportName: "createProvidersRouter" },
  },
];

export function findBackendContractCapability(id: string): BackendContractCapability | undefined {
  return BACKEND_CONTRACT_CAPABILITIES.find((capability) => capability.id === id);
}