import type { InkosProvider } from "../types.js";

export const AI360: InkosProvider = {
  id: "ai360",
  label: "360 智脑",
  api: "openai-completions",
  baseUrl: "https://api.360.cn/v1",
  checkModel: "360gpt2-pro",
  temperatureRange: [0, 2],
  defaultTemperature: 0.5,
  writingTemperature: 1,
  models: [
    { id: "360zhinao3-o1.5", displayName: "360Zhinao3 o1.5", maxOutput: 4096, contextWindowTokens: 128000, abilities: { reasoning: true, functionCall: true, search: true }, enabled: true },
    { id: "360zhinao2-o1.5", displayName: "360Zhinao2 o1.5", maxOutput: 4096, contextWindowTokens: 128000, abilities: { reasoning: true, functionCall: true, search: true } },
    { id: "360zhinao2-o1", displayName: "360Zhinao2 o1", maxOutput: 4096, contextWindowTokens: 128000, abilities: { reasoning: true } },
    { id: "360zhinao-pro-32k-thinking-vision", displayName: "360Zhinao Pro 32K Thinking Vision", maxOutput: 4096, contextWindowTokens: 32000, abilities: { vision: true }, enabled: true },
    { id: "360zhinao-turbo", displayName: "360Zhinao Turbo", maxOutput: 4096, contextWindowTokens: 32000, enabled: true },
    { id: "360zhinao-turbo-qwen-plus", displayName: "360Zhinao Turbo Qwen Plus", maxOutput: 4096, contextWindowTokens: 32000 },
    { id: "360gpt2-o1", displayName: "360GPT2 o1", maxOutput: 4096, contextWindowTokens: 128000, abilities: { reasoning: true } },
    { id: "360gpt2-pro", displayName: "360GPT2 Pro", maxOutput: 4096, contextWindowTokens: 32000, abilities: { functionCall: true, search: true } },
    { id: "360gpt-pro", displayName: "360GPT Pro", maxOutput: 4096, contextWindowTokens: 32000, abilities: { functionCall: true, search: true } },
    { id: "360gpt-pro-trans", displayName: "360GPT Pro Trans", maxOutput: 4096, contextWindowTokens: 4096 },
    { id: "360gpt-turbo", displayName: "360GPT Turbo", maxOutput: 4096, contextWindowTokens: 32000 },
    { id: "deepseek-v3.2", displayName: "DeepSeek V3.2", maxOutput: 4096, contextWindowTokens: 65536, abilities: { functionCall: true } },
    { id: "paratera/deepseek-v3.2", displayName: "DeepSeek V3.2 (Paratera)", maxOutput: 4096, contextWindowTokens: 4096, abilities: { functionCall: true } },
    { id: "sophnet/deepseek-v3.2", displayName: "DeepSeek V3.2 (SophNet)", maxOutput: 4096, contextWindowTokens: 4096, abilities: { functionCall: true } },
    { id: "deepseek-v3.2-speciale", displayName: "DeepSeek V3.2 Speciale", maxOutput: 4096, contextWindowTokens: 65536 },
    { id: "360/deepseek-r1", displayName: "DeepSeek R1", maxOutput: 4096, contextWindowTokens: 65536, abilities: { reasoning: true } },
    { id: "volcengine/doubao-seed-2-0-lite", displayName: "Doubao Seed 2.0 Lite", maxOutput: 4096, contextWindowTokens: 32000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "volcengine/doubao-seed-2-0-mini", displayName: "Doubao Seed 2.0 Mini", maxOutput: 4096, contextWindowTokens: 32000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "volcengine/doubao-seed-2-0-pro", displayName: "Doubao Seed 2.0 Pro", maxOutput: 4096, contextWindowTokens: 32000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "volcengine/doubao-seed-2-0-code", displayName: "Doubao Seed 2.0 Code", maxOutput: 4096, contextWindowTokens: 32000, abilities: { reasoning: true, vision: true, functionCall: true } },
  ],
};
