import type { InkosProvider } from "../types.js";

export const GITHUB_COPILOT: InkosProvider = {
  id: "githubCopilot",
  label: "GitHub Copilot",
  api: "openai-responses",
  baseUrl: "https://api.githubcopilot.com",
  checkModel: "gpt-4o",
  temperatureRange: [0, 2],
  defaultTemperature: 1,
  writingTemperature: 1,
  models: [
    { id: "gpt-5.4", displayName: "GPT-5.4", maxOutput: 4096, contextWindowTokens: 400000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, enabled: true, releasedAt: "2026-03-05" },
    { id: "gpt-5.4-mini", displayName: "GPT-5.4 mini", maxOutput: 4096, contextWindowTokens: 400000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, enabled: true, releasedAt: "2026-03-18" },
    { id: "gpt-5.3-codex", displayName: "GPT-5.3 Codex", maxOutput: 4096, contextWindowTokens: 400000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, releasedAt: "2026-02-05" },
    { id: "gpt-5.2", displayName: "GPT-5.2", maxOutput: 4096, contextWindowTokens: 192000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, releasedAt: "2025-12-11" },
    { id: "gpt-5.2-codex", displayName: "GPT-5.2 Codex", maxOutput: 4096, contextWindowTokens: 400000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, releasedAt: "2025-12-18" },
    { id: "gpt-5.1", displayName: "GPT-5.1", maxOutput: 4096, contextWindowTokens: 192000, abilities: { reasoning: true, vision: true, functionCall: true }, releasedAt: "2025-11-13" },
    { id: "gpt-5-mini", displayName: "GPT-5 mini", maxOutput: 4096, contextWindowTokens: 192000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, releasedAt: "2025-08-07" },
    { id: "gpt-4.1", displayName: "GPT-4.1", maxOutput: 4096, contextWindowTokens: 128000, abilities: { vision: true, functionCall: true }, releasedAt: "2025-04-14" },
    { id: "claude-opus-4.6", displayName: "Claude Opus 4.6", maxOutput: 4096, contextWindowTokens: 139000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, enabled: true, releasedAt: "2026-02-05" },
    { id: "claude-opus-4.6-fast", displayName: "Claude Opus 4.6 (Fast Mode)", maxOutput: 4096, contextWindowTokens: 139000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, releasedAt: "2026-02-05" },
    { id: "claude-sonnet-4.6", displayName: "Claude Sonnet 4.6", maxOutput: 4096, contextWindowTokens: 139000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, enabled: true, releasedAt: "2026-02-17" },
    { id: "claude-opus-4.5", displayName: "Claude Opus 4.5", maxOutput: 4096, contextWindowTokens: 139000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, releasedAt: "2025-11-24" },
    { id: "claude-sonnet-4.5", displayName: "Claude Sonnet 4.5", maxOutput: 4096, contextWindowTokens: 139000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, releasedAt: "2025-09-29" },
    { id: "claude-haiku-4.5", displayName: "Claude Haiku 4.5", maxOutput: 4096, contextWindowTokens: 139000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, enabled: true, releasedAt: "2025-10-16" },
    { id: "claude-sonnet-4", displayName: "Claude Sonnet 4", maxOutput: 4096, contextWindowTokens: 139000, abilities: { reasoning: true, vision: true, functionCall: true }, releasedAt: "2025-05-23" },
    { id: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro Preview", maxOutput: 4096, contextWindowTokens: 173000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, enabled: true, releasedAt: "2026-02-19" },
    { id: "gemini-3-flash-preview", displayName: "Gemini 3 Flash Preview", maxOutput: 4096, contextWindowTokens: 173000, abilities: { reasoning: true, vision: true, functionCall: true }, releasedAt: "2025-12-17" },
    { id: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro", maxOutput: 4096, contextWindowTokens: 173000, abilities: { reasoning: true, vision: true, functionCall: true }, releasedAt: "2025-06-17" },
    { id: "grok-code-fast-1", displayName: "Grok Code Fast 1", maxOutput: 4096, contextWindowTokens: 173000, abilities: { reasoning: true, functionCall: true, structuredOutput: true }, enabled: true, releasedAt: "2025-08-27" },
    { id: "oswe-vscode-prime", displayName: "Raptor mini", maxOutput: 4096, contextWindowTokens: 264000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true }, enabled: true },
    { id: "oswe-vscode-secondary", displayName: "Raptor mini (Secondary)", maxOutput: 4096, contextWindowTokens: 264000, abilities: { reasoning: true, vision: true, functionCall: true, structuredOutput: true } },
  ],
};
