import type { InkosProvider } from "../types.js";

export const PPIO: InkosProvider = {
  id: "ppio",
  label: "PPIO",
  api: "openai-completions",
  baseUrl: "https://api.ppinfra.com/v3/openai",
  checkModel: "deepseek/deepseek-v3",
  temperatureRange: [0, 2],
  defaultTemperature: 0.7,
  writingTemperature: 1,
  models: [
    { id: "deepseek/deepseek-r1/community", displayName: "DeepSeek: DeepSeek R1 (Community)", maxOutput: 4096, contextWindowTokens: 64000, abilities: { reasoning: true }, enabled: true },
    { id: "deepseek/deepseek-v3/community", displayName: "DeepSeek: DeepSeek V3 (Community)", maxOutput: 4096, contextWindowTokens: 64000, enabled: true },
    { id: "deepseek/deepseek-r1", displayName: "DeepSeek R1", maxOutput: 4096, contextWindowTokens: 64000, abilities: { reasoning: true }, enabled: true },
    { id: "deepseek/deepseek-v3", displayName: "DeepSeek V3", maxOutput: 4096, contextWindowTokens: 64000, enabled: true },
    { id: "deepseek/deepseek-r1-distill-llama-70b", displayName: "DeepSeek R1 Distill Llama 70B", maxOutput: 4096, contextWindowTokens: 32000, abilities: { reasoning: true }, enabled: true },
    { id: "deepseek/deepseek-r1-distill-qwen-32b", displayName: "DeepSeek: DeepSeek R1 Distill Qwen 32B", maxOutput: 4096, contextWindowTokens: 64000, abilities: { reasoning: true }, enabled: true },
    { id: "deepseek/deepseek-r1-distill-qwen-14b", displayName: "DeepSeek: DeepSeek R1 Distill Qwen 14B", maxOutput: 4096, contextWindowTokens: 64000, abilities: { reasoning: true }, enabled: true },
    { id: "deepseek/deepseek-r1-distill-llama-8b", displayName: "DeepSeek: DeepSeek R1 Distill Llama 8B", maxOutput: 4096, contextWindowTokens: 32000, abilities: { reasoning: true }, enabled: true },
    { id: "qwen/qwen-2.5-72b-instruct", displayName: "qwen/qwen-2.5-72b-instruct", maxOutput: 4096, contextWindowTokens: 32768, enabled: true },
    { id: "qwen/qwen-2-vl-72b-instruct", displayName: "qwen/qwen-2-vl-72b-instruct", maxOutput: 4096, contextWindowTokens: 32768, abilities: { vision: true }, enabled: true },
    { id: "meta-llama/llama-3.2-3b-instruct", displayName: "meta-llama/llama-3.2-3b-instruct", maxOutput: 4096, contextWindowTokens: 32768, enabled: true },
    { id: "qwen/qwen2.5-32b-instruct", displayName: "qwen/qwen2.5-32b-instruct", maxOutput: 4096, contextWindowTokens: 32000, enabled: true },
    { id: "baichuan/baichuan2-13b-chat", displayName: "baichuan/baichuan2-13b-chat", maxOutput: 4096, contextWindowTokens: 14336, enabled: true },
    { id: "meta-llama/llama-3.1-70b-instruct", displayName: "meta-llama/llama-3.1-70b-instruct", maxOutput: 4096, contextWindowTokens: 32768, enabled: true },
    { id: "meta-llama/llama-3.1-8b-instruct", displayName: "meta-llama/llama-3.1-8b-instruct", maxOutput: 4096, contextWindowTokens: 32768, enabled: true },
    { id: "01-ai/yi-1.5-34b-chat", displayName: "01-ai/yi-1.5-34b-chat", maxOutput: 4096, contextWindowTokens: 16384, enabled: true },
    { id: "01-ai/yi-1.5-9b-chat", displayName: "01-ai/yi-1.5-9b-chat", maxOutput: 4096, contextWindowTokens: 16384, enabled: true },
    { id: "thudm/glm-4-9b-chat", displayName: "thudm/glm-4-9b-chat", maxOutput: 4096, contextWindowTokens: 32768, enabled: true },
    { id: "qwen/qwen-2-7b-instruct", displayName: "qwen/qwen-2-7b-instruct", maxOutput: 4096, contextWindowTokens: 32768, enabled: true },
  ],
};
