import type { InkosProvider } from "../types.js";

export const VOLCENGINE: InkosProvider = {
  id: "volcengine",
  label: "火山引擎 (豆包)",
  api: "openai-completions",
  baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
  checkModel: "doubao-lite-32k",
  temperatureRange: [0, 1],
  defaultTemperature: 0.7,
  writingTemperature: 1,
  models: [
    { id: "doubao-seed-2.0-pro", displayName: "Doubao Seed 2.0 Pro", maxOutput: 128000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true }, enabled: true, releasedAt: "2026-02-15" },
    { id: "doubao-seed-2.0-lite", displayName: "Doubao Seed 2.0 Lite", maxOutput: 128000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true }, enabled: true, releasedAt: "2026-02-15" },
    { id: "doubao-seed-2.0-mini", displayName: "Doubao Seed 2.0 Mini", maxOutput: 128000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true }, releasedAt: "2026-02-15" },
    { id: "doubao-seed-2.0-code", displayName: "Doubao Seed 2.0 Code", maxOutput: 128000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true }, releasedAt: "2026-02-15" },
    { id: "doubao-seed-1.8", displayName: "Doubao Seed 1.8", maxOutput: 64000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true }, releasedAt: "2025-12-18" },
    { id: "doubao-seed-code", displayName: "Doubao Seed Code", maxOutput: 32000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "glm-4-7", displayName: "GLM-4.7", maxOutput: 128000, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true } },
    { id: "deepseek-v3.2", displayName: "DeepSeek V3.2", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true } },
    { id: "deepseek-v3.1", displayName: "DeepSeek V3.1", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true } },
    { id: "kimi-k2-thinking", displayName: "Kimi K2 Thinking", maxOutput: 32768, contextWindowTokens: 262144, abilities: { reasoning: true, functionCall: true } },
    { id: "kimi-k2", displayName: "Kimi K2", maxOutput: 32768, contextWindowTokens: 262144, abilities: { functionCall: true } },
    { id: "doubao-seed-1.6-vision", displayName: "Doubao Seed 1.6 Vision", maxOutput: 32000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "doubao-seed-1.6-thinking", displayName: "Doubao Seed 1.6 Thinking", maxOutput: 32000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "doubao-seed-1.6", displayName: "Doubao Seed 1.6", maxOutput: 32000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "doubao-seed-1.6-lite", displayName: "Doubao Seed 1.6 Lite", maxOutput: 32000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "doubao-seed-1.6-flash", displayName: "Doubao Seed 1.6 Flash", maxOutput: 32000, contextWindowTokens: 256000, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "doubao-1.5-ui-tars", displayName: "Doubao 1.5 UI TARS", maxOutput: 16000, contextWindowTokens: 131072, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "doubao-1.5-thinking-vision-pro", displayName: "Doubao 1.5 Thinking Vision Pro", maxOutput: 16000, contextWindowTokens: 131072, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "doubao-1.5-thinking-pro", displayName: "Doubao 1.5 Thinking Pro", maxOutput: 16000, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true } },
    { id: "doubao-1.5-thinking-pro-m", displayName: "Doubao 1.5 Thinking Pro M", maxOutput: 16000, contextWindowTokens: 131072, abilities: { reasoning: true, vision: true, functionCall: true } },
    { id: "deepseek-r1", displayName: "DeepSeek R1", maxOutput: 16384, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true } },
    { id: "deepseek-v3", displayName: "DeepSeek V3", maxOutput: 16384, contextWindowTokens: 128000, abilities: { functionCall: true } },
    { id: "doubao-1.5-pro-32k", displayName: "Doubao 1.5 Pro 32k", maxOutput: 16384, contextWindowTokens: 128000, abilities: { functionCall: true } },
    { id: "doubao-1.5-pro-256k", displayName: "Doubao 1.5 Pro 256k", maxOutput: 12288, contextWindowTokens: 256000 },
    { id: "doubao-1.5-lite-32k", displayName: "Doubao 1.5 Lite 32k", maxOutput: 12288, contextWindowTokens: 32768, abilities: { functionCall: true } },
    { id: "doubao-1.5-vision-pro-32k", displayName: "Doubao 1.5 Vision Pro 32k", maxOutput: 12288, contextWindowTokens: 32768, abilities: { vision: true, functionCall: true }, releasedAt: "2025-01-15" },
    { id: "doubao-1.5-vision-pro", displayName: "Doubao 1.5 Vision Pro", maxOutput: 16384, contextWindowTokens: 128000, abilities: { vision: true, functionCall: true }, releasedAt: "2025-03-28" },
    { id: "doubao-1.5-vision-lite", displayName: "Doubao 1.5 Vision Lite", maxOutput: 16384, contextWindowTokens: 128000, abilities: { vision: true, functionCall: true }, releasedAt: "2025-03-15" },
    { id: "doubao-lite-32k", displayName: "Doubao Lite 32k", maxOutput: 4096, contextWindowTokens: 32768 },
    { id: "doubao-pro-32k", displayName: "Doubao Pro 32k", maxOutput: 4096, contextWindowTokens: 32768 },
  ],
};
