import type { InkosProvider } from "../types.js";

export const ZHIPU: InkosProvider = {
  id: "zhipu",
  label: "智谱 GLM",
  api: "openai-completions",
  baseUrl: "https://open.bigmodel.cn/api/paas/v4",
  piProvider: "zai",
  checkModel: "glm-4-flash",
  temperatureRange: [0, 1],
  defaultTemperature: 0.95,
  writingTemperature: 0.95,
  models: [
    { id: "glm-5.1", displayName: "GLM-5.1", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true, search: true }, enabled: true, releasedAt: "2026-03-27" },
    { id: "glm-5-turbo", displayName: "GLM-5-Turbo", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true, search: true }, releasedAt: "2026-03-15" },
    { id: "glm-5", displayName: "GLM-5", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true, search: true }, enabled: true, releasedAt: "2026-02-12" },
    { id: "glm-4.7", displayName: "GLM-4.7", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true, search: true }, releasedAt: "2025-12-22" },
    { id: "glm-4.7-flash", displayName: "GLM-4.7-Flash", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true, search: true }, enabled: true, releasedAt: "2026-01-19" },
    { id: "glm-4.7-flashx", displayName: "GLM-4.7-FlashX", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true, search: true }, releasedAt: "2026-01-19" },
    { id: "glm-5v-turbo", displayName: "GLM-5V-Turbo", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, vision: true, functionCall: true, search: true }, enabled: true, releasedAt: "2026-04-02" },
    { id: "glm-4.6v", displayName: "GLM-4.6V", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, vision: true, functionCall: true, search: true }, releasedAt: "2025-12-08" },
    { id: "glm-4.6v-flashx", displayName: "GLM-4.6V-FlashX", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, vision: true, functionCall: true, search: true }, releasedAt: "2025-12-08" },
    { id: "glm-4.6v-flash", displayName: "GLM-4.6V-Flash", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, vision: true, functionCall: true, search: true }, releasedAt: "2025-12-08" },
    { id: "glm-4.6", displayName: "GLM-4.6", maxOutput: 131072, contextWindowTokens: 200000, abilities: { reasoning: true, functionCall: true, search: true }, releasedAt: "2025-09-08" },
    { id: "glm-4.5v", displayName: "GLM-4.5V", maxOutput: 16384, contextWindowTokens: 65536, abilities: { reasoning: true, vision: true, functionCall: true, search: true } },
    { id: "glm-4.5", displayName: "GLM-4.5", maxOutput: 98304, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true, search: true } },
    { id: "glm-4.5-x", displayName: "GLM-4.5-X", maxOutput: 98304, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true, search: true } },
    { id: "glm-4.5-air", displayName: "GLM-4.5-Air", maxOutput: 98304, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true, search: true } },
    { id: "glm-4.5-airx", displayName: "GLM-4.5-AirX", maxOutput: 98304, contextWindowTokens: 131072, abilities: { reasoning: true, functionCall: true, search: true } },
    { id: "glm-4.1v-thinking-flashx", displayName: "GLM-4.1V-Thinking-FlashX", maxOutput: 32768, contextWindowTokens: 65536, abilities: { reasoning: true, vision: true } },
    { id: "glm-4.1v-thinking-flash", displayName: "GLM-4.1V-Thinking-Flash", maxOutput: 32768, contextWindowTokens: 65536, abilities: { reasoning: true, vision: true } },
    { id: "glm-zero-preview", displayName: "GLM-Zero-Preview", maxOutput: 4096, contextWindowTokens: 16384, abilities: { reasoning: true } },
    { id: "glm-z1-air", displayName: "GLM-Z1-Air", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, search: true } },
    { id: "glm-z1-airx", displayName: "GLM-Z1-AirX", maxOutput: 32768, contextWindowTokens: 32768, abilities: { reasoning: true, search: true } },
    { id: "glm-z1-flashx", displayName: "GLM-Z1-FlashX", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, search: true } },
    { id: "glm-z1-flash", displayName: "GLM-Z1-Flash", maxOutput: 32768, contextWindowTokens: 131072, abilities: { reasoning: true, search: true } },
    { id: "glm-4-flash-250414", displayName: "GLM-4-Flash-250414", maxOutput: 32768, contextWindowTokens: 131072, abilities: { functionCall: true, search: true } },
    { id: "glm-4-flashx", displayName: "GLM-4-FlashX-250414", maxOutput: 4095, contextWindowTokens: 131072, abilities: { functionCall: true, search: true } },
    { id: "glm-4-long", displayName: "GLM-4-Long", maxOutput: 4095, contextWindowTokens: 1024000, abilities: { functionCall: true, search: true } },
    { id: "glm-4-air-250414", displayName: "GLM-4-Air-250414", maxOutput: 16384, contextWindowTokens: 131072, abilities: { functionCall: true, search: true } },
    { id: "glm-4-airx", displayName: "GLM-4-AirX", maxOutput: 4095, contextWindowTokens: 8192, abilities: { functionCall: true, search: true } },
    { id: "glm-4-plus", displayName: "GLM-4-Plus", maxOutput: 4095, contextWindowTokens: 131072, abilities: { functionCall: true, search: true } },
    { id: "glm-4-0520", displayName: "GLM-4-0520", maxOutput: 4096, contextWindowTokens: 131072, abilities: { functionCall: true, search: true } },
    { id: "glm-4v-flash", displayName: "GLM-4V-Flash", maxOutput: 1024, contextWindowTokens: 4096, abilities: { vision: true }, releasedAt: "2024-12-09" },
    { id: "glm-4v-plus-0111", displayName: "GLM-4V-Plus-0111", maxOutput: 8192, contextWindowTokens: 16000, abilities: { vision: true } },
    { id: "glm-4v", displayName: "GLM-4V", maxOutput: 1024, contextWindowTokens: 4096, abilities: { vision: true } },
    { id: "codegeex-4", displayName: "CodeGeeX-4", maxOutput: 32768, contextWindowTokens: 131072 },
    { id: "charglm-4", displayName: "CharGLM-4", maxOutput: 4000, contextWindowTokens: 8192 },
    { id: "emohaa", displayName: "Emohaa", maxOutput: 4000, contextWindowTokens: 8192 },
  ],
};
